# Generated by Django 2.2.1 on 2020-01-18 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_names', models.CharField(max_length=80)),
                ('tl_twts', models.CharField(max_length=20)),
                ('tl_sents', models.CharField(max_length=20)),
                ('tl_wrds', models.CharField(max_length=20)),
                ('tl_sylbs', models.CharField(max_length=20)),
                ('median', models.CharField(max_length=20)),
                ('read_scores', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DataView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=80)),
                ('tl_twt', models.CharField(max_length=20)),
                ('tl_wrd', models.CharField(max_length=20)),
                ('tl_sylb', models.CharField(max_length=20)),
                ('median', models.CharField(max_length=20)),
                ('read_score', models.CharField(max_length=20)),
                ('file_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_read_ability.StoreData')),
            ],
        ),
    ]
