# Generated by Django 2.2.1 on 2020-01-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_names', models.CharField(max_length=80)),
                ('tl_twts', models.CharField(max_length=20)),
                ('tl_wrds', models.CharField(max_length=20)),
                ('tl_sylbs', models.CharField(max_length=20)),
                ('median', models.CharField(max_length=20)),
                ('read_scores', models.CharField(max_length=20)),
            ],
        ),
    ]
